/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade05.view;

import java.util.Hashtable;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class InterfaceSlider extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceSlider
     */
    public InterfaceSlider() {
        initComponents();
        
        /* 
        Impossibilita a edição da caixa de texto por parte do usario, evita
        erros devido a entrada inválda   
        */
        txtResposta.setEditable(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtResposta = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inicioSlider = new javax.swing.JSlider();
        fimSlider = new javax.swing.JSlider();
        passoSlider = new javax.swing.JSlider();
        btnContar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResposta.setColumns(20);
        txtResposta.setLineWrap(true);
        txtResposta.setRows(5);
        jScrollPane1.setViewportView(txtResposta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 6, 109, 280));

        jLabel1.setText("INICIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 40, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("FIM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 30, 20));

        jLabel3.setText("PASSO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 20));

        inicioSlider.setMajorTickSpacing(1);
        inicioSlider.setMaximum(10);
        inicioSlider.setMinimum(1);
        inicioSlider.setPaintLabels(true);
        inicioSlider.setPaintTicks(true);
        inicioSlider.setValue(1);
        getContentPane().add(inicioSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 50));

        fimSlider.setMajorTickSpacing(1);
        fimSlider.setMaximum(15);
        fimSlider.setMinimum(6);
        fimSlider.setPaintLabels(true);
        fimSlider.setPaintTicks(true);
        fimSlider.setValue(6);
        getContentPane().add(fimSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 60));

        passoSlider.setMajorTickSpacing(1);
        passoSlider.setMaximum(5);
        passoSlider.setMinimum(1);
        passoSlider.setPaintLabels(true);
        passoSlider.setPaintTicks(true);
        passoSlider.setValue(1);
        getContentPane().add(passoSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 200, 50));

        btnContar.setText("CONTAR");
        btnContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 80, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade05/images/professor.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 190, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarActionPerformed
        // TODO add your handling code here:
        
        int inicio = inicioSlider.getValue();
        int fim = fimSlider.getValue();
        
        int passo = passoSlider.getValue();
        
        txtResposta.setText(""); // limpa antes de começar

for (int i = inicio; i <= fim; i += passo) {
    txtResposta.append(i + "\n");
}
        
        
    }//GEN-LAST:event_btnContarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceSlider().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContar;
    private javax.swing.JSlider fimSlider;
    private javax.swing.JSlider inicioSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider passoSlider;
    private javax.swing.JTextArea txtResposta;
    // End of variables declaration//GEN-END:variables
}
