/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

import java.awt.Font;
import javax.swing.JSpinner;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author User
 */
public class InterfaceGenio extends javax.swing.JFrame {

    /**
     * Creates new form interfaceGenio
     */
    public InterfaceGenio() {
        initComponents();
        
        // Torna o Spinner não editavel, evitando erros por entrada invalida
        ((JSpinner.DefaultEditor) spnValor.getEditor()).getTextField().setEditable(false);

        lblBalao.setForeground(UIManager.getColor("Label.foreground")); // Cor igual ao padrão de JLabel
        lblBalao.setFont(new Font("SansSerif", Font.BOLD, 12)); // Fonte maior e em negrito

        lblBalao.setText(
                       "<html>" +
                       "Vou pensar em um número<br>" +
                       "entre 1 a 5<br>" +
                       "Adivinhe qual é!" +
                       "</html>"
                );


                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtBalao = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnPapite = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        spnValor = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        lblBalao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        txtBalao.setEditable(false);
        txtBalao.setColumns(20);
        txtBalao.setLineWrap(true);
        txtBalao.setRows(5);
        txtBalao.setWrapStyleWord(true);
        txtBalao.setBorder(null);
        txtBalao.setFocusable(false);
        txtBalao.setOpaque(false);
        jScrollPane1.setViewportView(txtBalao);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/genio.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 200, 210));

        btnPapite.setText("PALPITE");
        btnPapite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPapiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPapite, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 90, 30));

        jLabel3.setText("VALOR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 60, 30));

        spnValor.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spnValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 70, 30));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBalao.setText("lblBalao");
        jPanel1.add(lblBalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 130));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 50, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 200, 130));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/balaoFala.png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 250, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPapiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPapiteActionPerformed
        // TODO add your handling code here:
        
        int aleatorio = (int)(Math.random() * 5) + 1;
        
        int numero = (int) spnValor.getValue();
        
        if(numero == aleatorio){
            // Fonte maior e em negrito
           lblBalao.setFont(new Font("SansSerif", Font.BOLD, 12));
           lblBalao.setText("\n\n       ACERTOU!!!");
        } else {
          lblBalao.setText("\n\n       ERROU!!!\n\nEu pensei no valor " + aleatorio);
        }
        
        
        // Cria o Timer que espera 3 segundos antes de "reiniciar"
        Timer reiniciarBalao = new Timer(3000, (e) -> {
                lblBalao.setText(
                       "<html>" +
                       "Vou pensar em um número<br>" +
                       "entre 1 a 5<br>" +
                       "Adivinhe qual é!" +
                       "</html>"
                );
        });
        reiniciarBalao.setRepeats(false); // Executa só uma vez
        reiniciarBalao.start();


    }//GEN-LAST:event_btnPapiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPapite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBalao;
    private javax.swing.JSpinner spnValor;
    private javax.swing.JTextArea txtBalao;
    // End of variables declaration//GEN-END:variables
}
