/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade09.view;

import br.com.ifba.atividade09.interfaces.InterfacePagamento;
import br.com.ifba.atividade09.service.PagamentoCartao;
import br.com.ifba.atividade09.service.PagamentoDinheiro;
import br.com.ifba.atividade09.service.PagamentoPix;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author User
 */
public class MenuPagamentos extends javax.swing.JFrame {

    /**
     * Creates new form MenuPagamentos
     */
    public MenuPagamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxMetodo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        bntPagar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtValorFinal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Forma de pagamento:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 30));

        cbxMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DINHEIRO", "CARTAO", "PIX" }));
        getContentPane().add(cbxMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, 30));

        jLabel2.setText("Seu nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 60, 30));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 200, 30));

        jLabel3.setText("Valor da compra:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, 30));

        txtValor.setText("0");
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 80, 30));

        bntPagar.setText("PAGAR");
        bntPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPagarActionPerformed(evt);
            }
        });
        getContentPane().add(bntPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 100, 30));

        jLabel4.setText("Valor Final:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 60, 30));

        txtValorFinal.setEditable(false);
        txtValorFinal.setText("0");
        getContentPane().add(txtValorFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 80, 30));

        jLabel5.setText("R$");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 20, 30));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 40, 30));

        jLabel7.setText("R$");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 20, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void bntPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPagarActionPerformed
        
        InterfacePagamento pagamento = null;
        String metodoSelecionado = (String) cbxMetodo.getSelectedItem();
        
        switch(metodoSelecionado){
        
            case "DINHEIRO":
                pagamento = new PagamentoDinheiro(); 
                break;
            case "CARTAO":
                pagamento = new PagamentoCartao(); 
                break;
            case "PIX":
                pagamento = new PagamentoPix(); 
                break;
        }
        
        // Resgata o nome
        String nome = txtNome.getText();
        
        // Resgata o valor da compra
        String valor = txtValor.getText();
        
        // #################################################################
        // Obter a data atual
        LocalDate dataAtual = LocalDate.now();

        // Definir o formato desejado
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yy");

        // Formatar a data
        String dataFormatada = dataAtual.format(formato);
        // #################################################################
                
        // Imprime o valor final
        double valorFinal = Double.parseDouble(pagamento.calcularTotal(valor));
        txtValorFinal.setText(pagamento.calcularTotal(valor));
        
        // Imprime o recibo
        pagamento.imprimirRecibo(nome, valor, dataFormatada, valorFinal); 
    }//GEN-LAST:event_bntPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPagamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntPagar;
    private javax.swing.JComboBox<String> cbxMetodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtValorFinal;
    // End of variables declaration//GEN-END:variables
}
