/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade03.view;

import java.awt.Color;
import java.time.LocalDate;

/**
 *
 * @author User
 */
public class InterfaceIdade extends javax.swing.JFrame {

    /**
     * Creates new form interfaceIdade
     */
    public InterfaceIdade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAnoNascimento = new javax.swing.JTextField();
        bntCalcular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        lblMensager = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ANO DE NASCIMENTO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 30));

        txtAnoNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoNascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtAnoNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 90, 30));

        bntCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade03/images/calculator.png"))); // NOI18N
        bntCalcular.setText("CALCULAR");
        bntCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(bntCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 130, 40));

        jLabel2.setText("SUA IDADE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 70, 30));
        getContentPane().add(txtIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 90, 30));
        getContentPane().add(lblMensager, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 350, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade03/images/data.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 160, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnoNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoNascimentoActionPerformed

    private void bntCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCalcularActionPerformed
        // TODO add your handling code here:
        
                // Captura a data atual
        LocalDate dataAtual = LocalDate.now();
        int anoAtual = dataAtual.getYear(); 
        
            
        // Verifica se a string contém apenas números
        String inputAno = txtAnoNascimento.getText();
        if (!inputAno.matches("\\d+")) {
            lblMensager.setText("Erro: Digite apenas números");
            lblMensager.setForeground(new Color(255, 0, 0));
            txtIdade.setText("0");
        return; // Sai do método sem executar o restante
        }
        
        int anoNascimento = Integer.parseInt(txtAnoNascimento.getText());
        
       
        boolean valid = true;
            if (anoNascimento < 1900 || anoNascimento > anoAtual) {
                lblMensager.setText("Erro: Intervalo de tempo invalido");
                lblMensager.setForeground(new Color(255, 0, 0)); // RGB: Vermelho
                valid = false;
            }

        int idade = anoAtual - anoNascimento;  
        
        if(valid) {
           lblMensager.setForeground(null); // Remove a cor personalizada e volta ao padrão do L&F
           lblMensager.setText(null);
           txtIdade.setText(Integer.toString(idade));
        } else if(!valid){
            txtIdade.setText(Integer.toString(0));
        }
    }//GEN-LAST:event_bntCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceIdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceIdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceIdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceIdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceIdade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblMensager;
    private javax.swing.JTextField txtAnoNascimento;
    private javax.swing.JTextField txtIdade;
    // End of variables declaration//GEN-END:variables
}
